# Website's icon url.
favicon: /images/favicon.ico

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
logo:
  text: My Notebook
# logo:

article:
  # Show word count and estimated reading time.
  readtime: false
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: github

# Navigation bar menu links.
menu:
  Home: /
  # Archives: /archives
  About: /about
  # change homepage to archive pages        kkdba: 20181012
  # mv layout/archive.ejs layout/index.ejs  kkdba: 20181012

# Search plugin settings.
search:
  type: insight

# Share plugin settings.
share:
  type:
  install_url:

# Comment plugin settings.
comment:
  type:
  shortname:

# Other plugins and their settings.
plugins:
  mathjax: false
  gallery: false
  google-analytics:
    tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
# navbar_links:
  # GitHub:
    # icon:
    # url:

# Links at the bottom of the page.
# footer_links:
  # GitHub:
